version: '3.3'

services:
  api:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: nest_api
    ports: 
      - 3000:3000
  front:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: react_front
    ports: 
      - 3001:3000